name: Deploy App to Server

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/warung_online:latest

      - name: Connect to server using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop warungContainer
            docker rm warungContainer
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/warung_online
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/warung_online
            docker run -d -p 80:80 -e JWT_KEY=${{ secrets.JWT_KEY }} -e CLOUD_NAME=${{ secrets.CLOUD_NAME }} -e KEY_API_SECRET=${{ secrets.KEY_API_SECRET }} -e KEY_API=${{ secrets.KEY_API }} -e KEY_SERVER_MIDTRANS=${{ secrets.KEY_SERVER_MIDTRANS }} -e DBUSER=${{ secrets.DBUSER }} -e DBPASS=${{ secrets.DBPASS }} -e DBHOST=${{ secrets.DBHOST }} -e DBPORT=${{ secrets.DBPORT }} -e DBNAME=${{ secrets.DBNAME }} --name warungContainer ${{ secrets.DOCKERHUB_USERNAME }}/warung_online:latest
